# Generated by Django 3.0.4 on 2020-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='io_register_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (0, '未知')], verbose_name='性别')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('cid', models.CharField(max_length=18, verbose_name='身份证号')),
                ('addr', models.CharField(max_length=128, verbose_name='住址')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '出入登记',
                'verbose_name_plural': '出入登记',
            },
        ),
    ]
